# examples/recovery_experiment.py
# ─────────────────────────────────────────────────────────────────────────────
# Recovery experiment: can the ES pipeline rediscover a known limit cycle?
#
# Procedure:
#   1. Build a known cyclic CTLN (an n-cycle: 0 → 1 → 2 → ... → n-1 → 0) and
#      simulate it. Its trajectory is a clean limit cycle by Curto-Morrison.
#   2. Warm-start the soft topology with logits biased toward that cycle plus
#      small Gaussian noise — so ES starts inside the cycle's attractor basin
#      and only has to refine, not discover topology from scratch.
#   3. Train ES to match the reference trajectory.
#   4. Verify:
#        (a) trajectories from many ICs converge onto the reference orbit,
#        (b) extract_adjacency returns the original cycle structure.
#
# This is the sanity check that should pass before any random-init experiment.
# ─────────────────────────────────────────────────────────────────────────────

import matplotlib as mpl

mpl.use("Agg")  # remove for interactive display

from pathlib import Path

import jax
import jax.numpy as jnp
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
from matplotlib import gridspec

from oscillon.dynamics import simulate
from oscillon.topology import (
    SoftNetworkSpec,
    extract_adjacency,
    gate_matrix,
    init_params_from_adjacency,
    make_param_to_model,
)
from oscillon.train.es import openai_es

script_dir = Path(__file__).parent
output_dir = script_dir / "images"
output_dir.mkdir(exist_ok=True)


# ── Reference network: a clean n-cycle CTLN ───────────────────────────────
n = 5
eps, delta, th = 0.10, 0.50, 0.10

# Canonical n-cycle: edge j → (j+1) mod n, encoded as A[i, j] where i=(j+1)%n
A_ref = np.zeros((n, n), dtype=bool)
for j in range(n):
    A_ref[(j + 1) % n, j] = True

# Discrete CTLN weight matrix in the standard rule
W_ref = jnp.asarray(np.where(A_ref, -1.0 + eps, -1.0 - delta) * (1 - np.eye(n)))
theta_ref = jnp.full((n,), th)

# Slightly asymmetric x0 to break the symmetry of the cycle and pick a phase
dt, n_steps = 0.1, 600
x0 = 0.1 * jnp.ones((n,)) + 0.02 * jnp.array([1.0, 0.0, -1.0, 0.0, 1.0])
ref_traj = simulate(W_ref, theta_ref, x0, dt=dt, n_steps=n_steps)

print(f"Reference: {int(A_ref.sum())}-edge cycle on n={n} nodes")


# ── Soft-topology network with warm-start init ────────────────────────────
spec = SoftNetworkSpec(n=n, eps=eps, delta=delta, learn_theta=True, theta_init=th)
to_model = make_param_to_model(spec)
key = jax.random.PRNGKey(0)

# Warm start: bias z toward the reference cycle plus noise
params0 = init_params_from_adjacency(
    spec,
    key,
    A_ref,
    edge_logit=3.0,
    non_edge_logit=-3.0,
    noise_std=0.6,
)


# ── Fitness: MSE to the reference trajectory (full multivariate) ──────────
# Target is generated by a real CTLN, so it lives inside the family — unlike
# the sinusoidal target in the previous demo, this one is actually reachable.
def fitness(params):
    W, theta = to_model(params)
    xs = simulate(W, theta, x0, dt=dt, n_steps=n_steps)
    return -jnp.mean((xs - ref_traj) ** 2)


print(f"n_params = {spec.n_params} (z logits: {spec.n_edges}, theta drives: {spec.n})")
print(f"init reward:  {float(fitness(params0)):+.5f}")

# ── Train ─────────────────────────────────────────────────────────────────
params, history = openai_es(
    fitness,
    params0,
    key,
    n_iters=80,
    pop=64,
    sigma=0.1,
    lr=0.05,
    verbose_every=20,
)
print(f"final reward: {float(fitness(params)):+.5f}")


# ── Recovery metrics (edge level) ─────────────────────────────────────────
A_disc = extract_adjacency(spec, params[: spec.n_edges])
np.fill_diagonal(A_disc, False)

TP = int((A_disc & A_ref).sum())
FP = int((A_disc & ~A_ref).sum())
FN = int((~A_disc & A_ref).sum())

print("\nRecovery (gate > 0.5 threshold):")
print(f"  true positives:  {TP} / {int(A_ref.sum())}  (cycle edges recovered)")
print(f"  false positives: {FP}                      (spurious edges)")
print(f"  false negatives: {FN}                      (cycle edges missed)")


# ── Multi-IC test: convergence to the reference orbit ─────────────────────
Wf, thetaf = to_model(params)
test_key = jax.random.PRNGKey(42)
n_ics = 8
ic_keys = jax.random.split(test_key, n_ics)
test_x0s = jnp.stack(
    [jax.random.uniform(k, (n,), minval=0.0, maxval=0.15) for k in ic_keys]
)
multi_traj = jax.vmap(lambda ic: simulate(Wf, thetaf, ic, dt=dt, n_steps=n_steps))(
    test_x0s
)
multi_traj_np = np.asarray(multi_traj)


# ── Visualization ──────────────────────────────────────────────────────────
def _draw_graph(ax, A_or_G, n, palette, title, highlight_edges=None):
    """Render either a boolean adjacency or a continuous gate matrix.

    If highlight_edges is a list of (j, i) tuples, those edges are drawn in
    a distinguishing color (used to mark the reference cycle on the
    discovered-topology plot).
    """
    DG = nx.DiGraph()
    DG.add_nodes_from(range(n))

    if A_or_G.dtype == bool:  # discrete reference adjacency
        for i in range(n):
            for j in range(n):
                if i != j and A_or_G[i, j]:
                    DG.add_edge(j, i, weight=1.0)
    else:  # continuous gate matrix
        for i in range(n):
            for j in range(n):
                if i != j:
                    DG.add_edge(j, i, weight=float(A_or_G[i, j]))

    pos = nx.circular_layout(DG)
    cstyle = "arc3,rad=0.18"

    edges_drawn = list(DG.edges(data=True))
    strong = [(u, v) for u, v, d in edges_drawn if d["weight"] > 0.5]
    weak = [(u, v) for u, v, d in edges_drawn if 0.05 < d["weight"] <= 0.5]

    if weak:
        nx.draw_networkx_edges(
            DG,
            pos,
            ax=ax,
            edgelist=weak,
            edge_color=[DG[u][v]["weight"] for u, v in weak],
            edge_cmap=plt.cm.Greys,
            edge_vmin=0.0,
            edge_vmax=0.8,
            width=[0.4 + DG[u][v]["weight"] * 1.5 for u, v in weak],
            alpha=0.3,
            arrows=True,
            arrowsize=8,
            connectionstyle=cstyle,
        )
    if strong:
        # Highlight the reference-cycle edges in a distinct color
        if highlight_edges is not None:
            hl_set = set(highlight_edges)
            cyc = [(u, v) for u, v in strong if (u, v) in hl_set]
            other = [(u, v) for u, v in strong if (u, v) not in hl_set]

            if other:
                nx.draw_networkx_edges(
                    DG,
                    pos,
                    ax=ax,
                    edgelist=other,
                    edge_color="orange",
                    width=[1.5 + DG[u][v]["weight"] * 3.0 for u, v in other],
                    alpha=0.85,
                    arrows=True,
                    arrowsize=15,
                    connectionstyle=cstyle,
                )
            if cyc:
                nx.draw_networkx_edges(
                    DG,
                    pos,
                    ax=ax,
                    edgelist=cyc,
                    edge_color="crimson",
                    width=[2.0 + DG[u][v]["weight"] * 3.0 for u, v in cyc],
                    alpha=0.95,
                    arrows=True,
                    arrowsize=17,
                    connectionstyle=cstyle,
                )
        else:
            nx.draw_networkx_edges(
                DG,
                pos,
                ax=ax,
                edgelist=strong,
                edge_color="crimson",
                width=[2.0 + DG[u][v]["weight"] * 3.0 for u, v in strong],
                alpha=0.9,
                arrows=True,
                arrowsize=15,
                connectionstyle=cstyle,
            )

    nx.draw_networkx_nodes(
        DG,
        pos,
        ax=ax,
        node_color=[palette[i] for i in range(n)],
        node_size=560,
        alpha=0.95,
        edgecolors="white",
        linewidths=1.5,
    )
    nx.draw_networkx_labels(
        DG,
        pos,
        ax=ax,
        labels={i: f"n{i}" for i in range(n)},
        font_color="white",
        font_size=9,
        font_weight="bold",
    )
    ax.set_title(title, fontsize=10)
    ax.axis("off")


def visualize(save_path=output_dir / "demo_plot.png"):
    palette = plt.cm.tab10(np.linspace(0, 0.9, n))
    ic_colors = plt.cm.plasma(np.linspace(0.1, 0.9, n_ics))
    burn = n_steps // 2

    ref_np = np.asarray(ref_traj)
    Gf = gate_matrix(spec, params[: spec.n_edges])
    t_np = np.arange(n_steps) * dt

    # Reference cycle as a set of (j, i) edges for highlighting
    ref_edges = [(j, (j + 1) % n) for j in range(n)]

    fig = plt.figure(figsize=(17, 10))
    gs = gridspec.GridSpec(2, 3, hspace=0.48, wspace=0.36)

    # ── [0, 0]  Multi-IC phase portrait: do trajectories find the orbit? ─
    ax1 = fig.add_subplot(gs[0, 0])
    # Reference orbit (steady state)
    ax1.plot(
        ref_np[burn:, 0],
        ref_np[burn:, 1],
        "k--",
        lw=2.2,
        label="Reference orbit",
        alpha=0.85,
        zorder=4,
    )
    # Trained trajectories from many ICs
    for i in range(n_ics):
        ax1.plot(
            multi_traj_np[i, :burn, 0],
            multi_traj_np[i, :burn, 1],
            color=ic_colors[i],
            lw=0.5,
            alpha=0.2,
            zorder=1,
        )
        ax1.plot(
            multi_traj_np[i, burn:, 0],
            multi_traj_np[i, burn:, 1],
            color=ic_colors[i],
            lw=1.4,
            alpha=0.75,
            zorder=3,
        )
        ax1.scatter(
            multi_traj_np[i, 0, 0],
            multi_traj_np[i, 0, 1],
            color=ic_colors[i],
            s=22,
            edgecolors="white",
            linewidths=0.7,
            zorder=5,
        )
    ax1.set_xlabel("Neuron 0", fontsize=10)
    ax1.set_ylabel("Neuron 1", fontsize=10)
    ax1.set_title(
        f"Multi-IC Phase Portrait ({n_ics} starts)\n"
        "Trajectories collapse onto reference ⇒ recovery",
        fontsize=10,
    )
    ax1.legend(fontsize=8, loc="upper right")

    # ── [0, 1]  All-neuron time series: trained vs reference ──────────────
    ax2 = fig.add_subplot(gs[0, 1])
    xsf = np.asarray(simulate(Wf, thetaf, x0, dt=dt, n_steps=n_steps))
    for i in range(n):
        ax2.plot(
            t_np, ref_np[:, i], color=palette[i], lw=2.5, alpha=0.35, zorder=1
        )  # reference
        ax2.plot(
            t_np,
            xsf[:, i],
            color=palette[i],
            lw=1.3,
            alpha=0.95,
            zorder=2,
            label=f"n{i}",
        )  # trained
    ax2.axvline(burn * dt, color="gray", lw=0.8, linestyle=":", alpha=0.6)
    ax2.set_xlabel("Time", fontsize=10)
    ax2.set_ylabel("Activity", fontsize=10)
    ax2.set_title(
        "All-Neuron Trajectories\n(thick=reference, thin=trained)", fontsize=10
    )
    ax2.legend(fontsize=8, ncol=2, loc="upper right")

    # ── [0, 2]  Learning curve ────────────────────────────────────────────
    ax3 = fig.add_subplot(gs[0, 2])
    ax3.plot(history, color="#27ae60", lw=2)
    ax3.axhline(history[-1], color="gray", lw=1, linestyle="--", alpha=0.6)
    ax3.set_xlabel("Generation", fontsize=10)
    ax3.set_ylabel("Best reward", fontsize=10)
    ax3.set_title("ES Learning Curve", fontsize=11)
    ax3.text(
        0.97,
        0.06,
        f"final: {history[-1]:.4f}",
        transform=ax3.transAxes,
        ha="right",
        va="bottom",
        fontsize=9,
        color="gray",
    )

    # ── [1, 0]  Reference topology ────────────────────────────────────────
    ax4 = fig.add_subplot(gs[1, 0])
    _draw_graph(
        ax4, A_ref, n, palette, f"Reference: {n}-cycle ({int(A_ref.sum())} edges)"
    )

    # ── [1, 1]  Discovered topology (cycle edges highlighted) ─────────────
    ax5 = fig.add_subplot(gs[1, 1])
    title = f"Discovered Topology\nTP={TP}/{int(A_ref.sum())}   FP={FP}   FN={FN}"
    _draw_graph(ax5, Gf, n, palette, title, highlight_edges=ref_edges)
    ax5.legend(
        handles=[
            mpatches.Patch(color="crimson", label="cycle edge"),
            mpatches.Patch(color="orange", label="spurious"),
        ],
        loc="lower right",
        fontsize=7,
        framealpha=0.6,
    )

    # ── [1, 2]  Gate heatmap with reference cycle marked ──────────────────
    ax6 = fig.add_subplot(gs[1, 2])
    cmap = plt.cm.RdYlGn.copy()
    cmap.set_bad("white")
    Gf_d = Gf.copy().astype(float)
    np.fill_diagonal(Gf_d, np.nan)

    im = ax6.imshow(Gf_d, cmap=cmap, vmin=0, vmax=1, aspect="auto")
    for i in range(n):
        for j in range(n):
            if i != j:
                val = Gf[i, j]
                tc = "white" if (val > 0.7 or val < 0.25) else "black"
                ax6.text(
                    j, i, f"{val:.2f}", ha="center", va="center", fontsize=7, color=tc
                )
    # Box the reference-cycle cells
    for j in range(n):
        i = (j + 1) % n
        ax6.add_patch(
            plt.Rectangle(
                (j - 0.5, i - 0.5),
                1,
                1,
                fill=False,
                edgecolor="blue",
                lw=2.5,
            )
        )

    ax6.set_xticks(range(n))
    ax6.set_yticks(range(n))
    ax6.set_xticklabels([f"n{j}" for j in range(n)], fontsize=8)
    ax6.set_yticklabels([f"n{i}" for i in range(n)], fontsize=8)
    ax6.set_xlabel("Source  j", fontsize=9)
    ax6.set_ylabel("Target  i", fontsize=9)
    ax6.set_title(
        "Gate Matrix sigmoid(z_ij)\nblue boxes = reference cycle edges", fontsize=10
    )
    plt.colorbar(
        im, ax=ax6, fraction=0.046, pad=0.04, label="0 = non-edge   →   1 = edge"
    )

    fig.suptitle(
        f"oscillon — Recovery Experiment ({n}-cycle CTLN)",
        fontsize=14,
        fontweight="bold",
    )
    fig.savefig(save_path, dpi=150, bbox_inches="tight")
    print(f"Saved → {save_path}")
    plt.show()


visualize()
